### ISSUE TITLE
M1 support

### ISSUE THREAD

**Issue by revolter** [singular-labs/Singular-iOS-SDK#22]
Add support for running an app using Singular SDK on M1 Macs in the Simulator app.

In other words, if you're using the Singular SDK alongside another SDK that does support M1's architecture, trying to run the app in the Simulator fails. So we're blocked using only real devices.

The `.xcframework` should bundle the arm64 binary for Simulator.

**Comment by revolter** [comment]
The error that I'm receiving is this:

```
Could not find module 'FBSDKCoreKit' for target 'x86_64-apple-ios-simulator'; found: arm64, arm64-apple-ios-simulator, at: /Users/revolt/Library/Developer/Xcode/DerivedData/Mondly-dsjsiejaojowwseybqfkevcqdywu/Build/Products/Debug-iphonesimulator/FBSDKCoreKit/FBSDKCoreKit.framework/Modules/FBSDKCoreKit.swiftmodule
```

And this is because the Facebook SDK doesn't offer anymore support for x86_64 simulators, but only for the new arm64 simulators. So, the Singular SDK should also provide support for arm64 simulators.

**Comment by omribaraksingular** [comment]
Hi @revolter , 

Thanks for bringing this to our attention. 
Singular iOS latest SDK supports both x86_64 and  arm64 simulators. 

Best, 
Omri Barak 
Product Manager

**Comment by revolter** [comment]
I can confirm that it works 🎉 Thank you!
