### ISSUE TITLE
Not working, getting 22 Errors in Xcode.

### ISSUE THREAD

**Issue by ahmadnaeem908** [singular-labs/Singular-iOS-SDK#38]
I have followed all the steps of integration of Singular-iOS-SDK, but it's not working. Please look into it. Thanks

<img width="1202" alt="Screenshot 2023-03-07 at 6 57 43 AM" src="https://user-images.githubusercontent.com/56918808/223299663-f0efac60-37a7-48ec-8d6a-36a4dc237605.png">

**Comment by shefdanny** [comment]
Closing this.
If this is still relevant please contact our support
https://support.singular.net/hc/en-us/requests/new
