### ISSUE TITLE
Remove dependency to deprecated iAd framework

### ISSUE THREAD

**Issue by bpoplauschi** [singular-labs/Singular-iOS-SDK#47]
Hi everyone!

According to Apple, they have deprecated the `iAd.framework` with a plan to remove it from the iOS entirely in the future.
Details can be found at several places like:
- https://developer.apple.com/documentation/iad
- https://developer.apple.com/documentation/iad/iad_changelog 
- https://developer.apple.com/documentation/iad/deprecated_symbols# 

It seems the Singular SDK still depends on the `iAd.framework`, at least per the CocoaPods podspec dependencies
`spec.ios.frameworks  = 'AdSupport', 'Security', 'SystemConfiguration', 'iAd', 'StoreKit', 'WebKit'`.

Is the `iAd.framework` still used by the `Singular` SDK? Can it be removed from the podspec in a future version?

Any feedback and help is much appreciated!
Thank you!

PS: Thanks for supporting a GitHub repo so it's easy to communicate this kind of feedback! :)

**Comment by shefdanny** [comment]
Hey @bpoplauschi,
We appreciate your communication. It is our standard practice at Singular to consistently monitor all policy changes initiated by Apple and to adapt our actions accordingly. In line with our established plan, the iAd framework is scheduled for removal in the upcoming release.

**Comment by bpoplauschi** [comment]
Much appreciated @shefdanny!
